
name: Node.js CI

on:
  push:
    branches: [ master, development ]

jobs:

#   params:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
    
#     outputs:
#       package_name:                   ${{ steps.inputs.outputs.package.name }}
#       crucible-registry:              ${{ steps.inputs.outputs.crucible_registry }}
#       base-registry:                  ${{ steps.inputs.outputs.base_registry }}
#       base-img-name:                  ${{ steps.inputs.outputs.base_image_name }}
#       base-img-tag:                   ${{ steps.inputs.outputs.base_image_tag }}
    
#     steps:
#       - name: Checkout Codebase
#         uses: actions/checkout@v3

#       - name: Get Inputs
#         id:   inputs
#         uses: zoexx/github-action-json-file-properties@release
#         with:
#           file_path: "./recipe/cmake.json"
#           prop_path: "package.name"

#       - name: Echo Inputs
#         run: |
#           echo ${{steps.inputs.outputs.value}}
          
  get_inputs:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
      
#             echo "::set-output name=json::$file_contents"

        - name: Get Inputs
          id:   inputs
          run: |
                  package_name=$( cat ./recipe/cmake.json | jq -r '.package.name' )
                  echo "::set-output name=package_kind::$package_name"
                  package_kind=$( cat ./recipe/cmake.json | jq -r '.package.kind' )
                  echo "::set-output name=package_kind::$package_kind"
            
                     
