
name: Node.js CI

on:
  push:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    

  read-json-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Read JSON file
        id: read-json
        run: |
          file_contents=$(cat ./recipe/cmake.json)
          echo "::set-output name=json::$file_contents"
      
      - name: Extract package name from JSON
        id: extract-package-name
        run: |
          package_name=$(echo ${{ steps.read-json.outputs.json }} | jq -r '.package.name')
          echo "::set-output name=package-name::$package_name"
      
      - name: Use package name
        run: |
          echo "Package name: ${{ steps.extract-package-name.outputs.package-name }}"
